name: Context testing
on:
  push:

jobs:
  build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: configurar nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 20
            - name: valida versao
              id: repo_vars
              run: |
                  output=$(node -e "
                  let versao = require('./package.json').version;
                  process.env.VERSAO = versao
                  if(/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.test(versao)){
                    console.log('docker-bb-local')
                  } else {
                    console.log('docker-bb-dev-local')
                  }") 
                  echo "REPOSITORY=$output">> $GITHUB_ENV
            - name: setup jfrog cli
              uses: jfrog/setup-jfrog-cli@v4.1.2
              env:
                JF_URL: https://binarios.intranet.bb.com.br
                JF_USER: ${{ secrets.ATF_BINARIOS_CI_USER }}
                JF_PASSWORD: ${{ secrets.ATF_BINARIOS_CI_PASS }}
            - name: usa versao
              run: |
                echo ${{ steps.repo_vars.outputs.REPOSITORY }}
                jf rt s "${{ steps.repo_vars.outputs.REPOSITORY }}/bb/aic/${GITHUB_ACTION_REPOSITORY}/${VERSAO}/manifest.json"
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  approved:
    permissions: write-all
    if: github.event.review.state == 'APPROVED' && github.event.review.user.username != 'vinszrt'
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: |
          echo "This PR wasn't approved by vinszrt"
          gh pr close ${{ github.event.pull_request.number }} -R ${{ github.repository }}
